//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using SpaceShipClass;
namespace AssemblyCSharp
{
	public class Pegasus : SpaceShip
	{
		public Pegasus ()
		{
			PrimaryWepon = 70;
			SecondaryWepon = 30;
			Shields = 150;
			Score = 0;
			Speed = 0;
			x = 0f;
			y = 0f;
			z = 0f;
			timesForSpecial = 5;
		}

		public override void setupBack ()
		{
			PrimaryWepon = 70;
			SecondaryWepon = 30;
			Shields = 150;
			Score = 0;
			Speed = 0;
			x = 0f;
			y = 0f;
			z = 0f;
			timesForSpecial = 5;
		}
	}
}

