//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using AssemblyCSharp;
namespace SpaceShipClass
{
	abstract public class SpaceShip
	{
		static public SpaceShip spaceship;
		static public string wichShip;
		public int PrimaryWepon {
			get;
			set;
		}
		public int SecondaryWepon {
			get;
			set;
		}
		public int Shields {
			get;
			set;
		}
		public int Score {
			get;
			set;
		}
		public float Speed {
			get;
			set;
		}
		public float x {
			get;
			set;
		}
		public float y {
			get;
			set;
		}
		public float z {
			get;
			set;
		}
		public bool specialWeponActive {
			get;
			set;
		}
		public int timesForSpecial {
			get;
			set;
		}
		public SpaceShip (){
		}
		public static SpaceShip Instance(string nameOfShip) {
			if (spaceship == null) {
				if(nameOfShip == "Interpid"){
					spaceship = new Interpid();
				}
				else if(nameOfShip == "Enterprise"){
					spaceship = new Enterprise();
				}
				else if(nameOfShip == "Pegasus"){
					spaceship = new Pegasus();
				}
				wichShip = nameOfShip;
			}
			return spaceship;
		}
		public void clearInstance(){
			spaceship = null;
		}
		public abstract void setupBack();
	}
}

